//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_TestCourse p_TestCourse;
        
        public static SteamVR_Input_ActionSet_TestCourse TestCourse
        {
            get
            {
                return SteamVR_Actions.p_TestCourse.GetCopy<SteamVR_Input_ActionSet_TestCourse>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_TestCourse = ((SteamVR_Input_ActionSet_TestCourse)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_TestCourse>("/actions/TestCourse")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.TestCourse};
        }
    }
}
